// Mocks generated by Mockito 5.0.8 from annotations
// in ditonton/test/presentation/pages/tvSeries_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;

import 'package:ditonton/domain/entities/tv_series.dart' as _i10;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_status_tv_series.dart'
    as _i4;
import 'package:ditonton/domain/usecases/delete_watchlist_tv_series.dart'
    as _i6;
import 'package:ditonton/domain/usecases/save_watchlist_tv_series.dart' as _i5;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetTVSeriesDetail extends _i1.Fake implements _i2.GetTVSeriesDetail {
}

class _FakeGetTVSeriesRecommendations extends _i1.Fake
    implements _i3.GetTVSeriesRecommendations {}

class _FakeGetWatchListStatus extends _i1.Fake
    implements _i4.GetDataTVSeriesWatchListStatus {}

class _FakeSaveWatchlist extends _i1.Fake
    implements _i5.SaveTVSeriesFromWatchlist {}

class _FakeRemoveWatchlist extends _i1.Fake
    implements _i6.DeleteTVSeriesFromWatchlist {}

class _FakeTVSeriesDetail extends _i1.Fake implements _i7.TVSeriesDetail {}

/// A class which mocks [TVSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailNotifier extends _i1.Mock
    implements _i8.TVSeriesDetailNotifier {
  MockTVSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVSeriesDetail),
          returnValue: _FakeGetTVSeriesDetail()) as _i2.GetTVSeriesDetail);
  @override
  _i3.GetTVSeriesRecommendations get getTVSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTVSeriesRecommendations),
              returnValue: _FakeGetTVSeriesRecommendations())
          as _i3.GetTVSeriesRecommendations);
  @override
  _i4.GetDataTVSeriesWatchListStatus get getWatchListStatusTVSeries =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatusTVSeries),
              returnValue: _FakeGetWatchListStatus())
          as _i4.GetDataTVSeriesWatchListStatus);
  @override
  _i5.SaveTVSeriesFromWatchlist get saveTVSeriesFromWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlist()) as _i5.SaveTVSeriesFromWatchlist);
  @override
  _i6.DeleteTVSeriesFromWatchlist get deleteTVSeriesFromWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlist())
          as _i6.DeleteTVSeriesFromWatchlist);
  @override
  _i7.TVSeriesDetail get tvSeries =>
      (super.noSuchMethod(Invocation.getter(#tvSeries),
          returnValue: _FakeTVSeriesDetail()) as _i7.TVSeriesDetail);
  @override
  _i9.RequestState get tvSeriesState =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.TVSeries> get tvSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRecommendations),
          returnValue: <_i10.TVSeries>[]) as List<_i10.TVSeries>);

  @override
  _i9.RequestState get recommendationStateTVSeries =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedTVSeriesToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTVSeriesDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTVSeriesDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> insertTVSeriesWatchlist(_i7.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvSeries]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> deleteFromWatchlist(_i7.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tvSeries]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
